<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/10/30 10:43:29

$database = new sfPropelDatabase();
$database->initialize(array (
  'phptype' => 'mysql',
  'port' => 3306,
  'hostspec' => '163.10.34.214',
  'database' => 'virtual',
  'username' => 'virtual',
  'password' => 'virtual',
), 'propel');
$this->databases['propel'] = $database;
