<?php
// auto-generated by sfLuceneProjectConfigHandler
// date: 2015/08/19 15:56:43

$config = array();



// processing  CMSIndex now...
$config['CMSIndex'] = array (
  'models' => 
  array (
    'Article' => 
    array (
      'partial' => 'article/search_result',
      'fields' => 
      array (
        'id' => 
        array (
          'type' => 'unindexed',
          'boost' => 1,
          'transform' => NULL,
        ),
        'title' => 
        array (
          'type' => 'text',
          'boost' => 1,
          'transform' => NULL,
        ),
        'article_title' => 
        array (
          'type' => 'text',
          'boost' => 1,
          'transform' => NULL,
        ),
        'heading' => 
        array (
          'type' => 'text',
          'boost' => 1,
          'transform' => NULL,
        ),
        'description' => 
        array (
          'type' => 'text',
          'boost' => 1,
          'transform' => NULL,
        ),
        'body' => 
        array (
          'type' => 'text',
          'boost' => 1,
          'transform' => 'strip_tags_with_whitespaces',
        ),
      ),
      'title' => 'title',
      'description' => 'heading',
      'indexer' => NULL,
      'peer' => 'ArticlePeer',
      'rebuild_limit' => 250,
      'validator' => 'isIndexable',
    ),
    'Section' => 
    array (
      'partial' => 'section/search_result',
      'fields' => 
      array (
        'id' => 
        array (
          'type' => 'unindexed',
          'boost' => 1,
          'transform' => NULL,
        ),
        'title' => 
        array (
          'type' => 'text',
          'boost' => 2,
          'transform' => NULL,
        ),
        'name' => 
        array (
          'type' => 'unindexed',
          'boost' => 1,
          'transform' => NULL,
        ),
        'description' => 
        array (
          'type' => 'text',
          'boost' => 1,
          'transform' => NULL,
        ),
      ),
      'title' => 'title',
      'description' => 'description',
      'indexer' => NULL,
      'peer' => 'SectionPeer',
      'rebuild_limit' => 250,
      'validator' => 'isIndexable',
    ),
    'Document' => 
    array (
      'partial' => 'search/document_search_result',
      'fields' => 
      array (
        'id' => 
        array (
          'type' => 'unindexed',
          'boost' => 1,
          'transform' => NULL,
        ),
        'title' => 
        array (
          'type' => 'text',
          'boost' => 1,
          'transform' => NULL,
        ),
        'document_title' => 
        array (
          'type' => 'text',
          'boost' => 1,
          'transform' => NULL,
        ),
        'content' => 
        array (
          'type' => 'text',
          'boost' => 1,
          'transform' => NULL,
        ),
        'uri' => 
        array (
          'type' => 'unindexed',
          'boost' => 1,
          'transform' => NULL,
        ),
      ),
      'title' => 'title',
      'description' => 'HTMLRepresentation',
      'indexer' => NULL,
      'peer' => 'DocumentPeer',
      'rebuild_limit' => 250,
      'validator' => 'isIndexable',
    ),
  ),
  'index' => 
  array (
    'encoding' => 'utf-8',
    'cultures' => 
    array (
      0 => 'es_AR',
    ),
    'stop_words' => 
    array (
      0 => 'uno',
      1 => 'una',
    ),
    'short_words' => 3,
    'analyzer' => 'utf8num',
    'case_sensitive' => false,
    'mb_string' => true,
    'param' => 
    array (
    ),
  ),
  'factories' => 
  array (
    'indexers' => 
    array (
    ),
    'results' => 
    array (
    ),
  ),
);
