<?php
// auto-generated by sfSecurityConfigHandler
// date: 2015/11/10 10:39:01
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
  ),
  'delete' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'reporter_admin',
        1 => 'designer_admin',
      ),
    ),
  ),
  'publish' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'reporter_admin',
        1 => 'designer_admin',
      ),
    ),
  ),
  'unpublish' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'reporter_admin',
        1 => 'designer_admin',
      ),
    ),
  ),
  'archive' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'reporter_admin',
        1 => 'designer_admin',
      ),
    ),
  ),
);
