<?php
// auto-generated by sfAdvancedAdmin
// date: 2015/08/19 15:56:59
?>
<ul class="sf_admin_actions">
  <li><?php echo button_to(__('list'), 'article/list?id='.$article->getId(), array (
  'class' => 'sf_admin_action_list',
)) ?></li>
</ul>
