<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/10/30 11:28:05
sfConfig::add(array(
  'sf_i18n_default_culture' => 'es_AR',
  'sf_i18n_source' => 'XLIFF',
  'sf_i18n_debug' => false,
  'sf_i18n_cache' => true,
  'sf_i18n_untranslated_prefix' => '[T]',
  'sf_i18n_untranslated_suffix' => '[/T]',
));
