<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/10/30 11:28:05
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'choique',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
