<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/08/19 15:52:47
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'choique',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
