<?php
// auto-generated by sfFilterConfigHandler
// date: 2015/10/30 11:28:05

list($class, $parameters) = (array) sfConfig::get('sf_rendering_filter', array('sfRenderingFilter', array (
)));
$filter = new $class();
$filter->initialize($this->context, $parameters);
$filterChain->register($filter);

list($class, $parameters) = (array) sfConfig::get('sf_web_debug_filter', array('sfWebDebugFilter', array (
)));
$filter = new $class();
$filter->initialize($this->context, $parameters);
$filterChain->register($filter);

// does this action require security?
if ($actionInstance->isSecure())
{
  if (!in_array('sfSecurityUser', class_implements($this->context->getUser())))
  {
    $error = 'Security is enabled, but your sfUser implementation does not implement sfSecurityUser interface';
    throw new sfSecurityException($error);
  }
  
list($class, $parameters) = (array) sfConfig::get('sf_security_filter', array('sfBasicSecurityFilter', array (
)));
$filter = new $class();
$filter->initialize($this->context, $parameters);
$filterChain->register($filter);
}

list($class, $parameters) = (array) sfConfig::get('sf_mobile_filter', array('choiqueMobileFilter', null));
$filter = new $class();
$filter->initialize($this->context, $parameters);
$filterChain->register($filter);

list($class, $parameters) = (array) sfConfig::get('sf_highlight_filter', array('sfLuceneHighlightFilter', null));
$filter = new $class();
$filter->initialize($this->context, $parameters);
$filterChain->register($filter);

list($class, $parameters) = (array) sfConfig::get('sf_csrf_filter', array('sfCSRFFilter', array (
  'secret' => '$3cr3t0_ch01qu3',
)));
$filter = new $class();
$filter->initialize($this->context, $parameters);
$filterChain->register($filter);

list($class, $parameters) = (array) sfConfig::get('sf_common_filter', array('sfCommonFilter', null));
$filter = new $class();
$filter->initialize($this->context, $parameters);
$filterChain->register($filter);

list($class, $parameters) = (array) sfConfig::get('sf_flash_filter', array('sfFlashFilter', array (
)));
$filter = new $class();
$filter->initialize($this->context, $parameters);
$filterChain->register($filter);

list($class, $parameters) = (array) sfConfig::get('sf_execution_filter', array('sfExecutionFilter', array (
)));
$filter = new $class();
$filter->initialize($this->context, $parameters);
$filterChain->register($filter);

list($class, $parameters) = (array) sfConfig::get('sf_UJS_filter', array('sfUJSFilter', null));
$filter = new $class();
$filter->initialize($this->context, $parameters);
$filterChain->register($filter);

