<?php
// auto-generated by sfRoutingConfigHandler
// date: 2015/08/19 15:52:47
$routes = sfRouting::getInstance();
$routes->setRoutes(
array (
  'homepage' => 
  array (
    0 => '/',
    1 => '/^[\\/]*$/',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'default',
      'action' => 'index',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'sitemap_xml' => 
  array (
    0 => '/sitemap_index',
    1 => '#^/sitemap_index\\.xml$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'sitemap',
      'action' => 'xmlIndex',
    ),
    5 => 
    array (
    ),
    6 => '.xml',
  ),
  'mobile' => 
  array (
    0 => '/mobile',
    1 => '#^/mobile$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'default',
      'action' => 'setMobileMode',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'no_mobile' => 
  array (
    0 => '/no_mobile',
    1 => '#^/no_mobile$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'default',
      'action' => 'unsetMobileMode',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'sitemap_xml_articles' => 
  array (
    0 => '/sitemap_articles',
    1 => '#^/sitemap_articles\\.xml$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'sitemap',
      'action' => 'xmlArticles',
    ),
    5 => 
    array (
    ),
    6 => '.xml',
  ),
  'sitemap_xml_sections' => 
  array (
    0 => '/sitemap_sections',
    1 => '#^/sitemap_sections\\.xml$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'sitemap',
      'action' => 'xmlSections',
    ),
    5 => 
    array (
    ),
    6 => '.xml',
  ),
  'events_search' => 
  array (
    0 => '/Eventos/*',
    1 => '#^/Eventos(?:\\/(.*))?$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'event',
      'action' => 'index',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'section_css' => 
  array (
    0 => '/section_css/:name',
    1 => '#^/section_css(?:\\/([^\\/]+))?$#',
    2 => 
    array (
      0 => 'name',
    ),
    3 => 
    array (
      'name' => 1,
    ),
    4 => 
    array (
      'module' => 'section',
      'action' => 'stylesheet',
      'sf_format' => 'css',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'article_preview' => 
  array (
    0 => '/ARTICLE_PREVIEW',
    1 => '#^/ARTICLE_PREVIEW$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'article',
      'action' => 'printPreviewBackend',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'template_preview' => 
  array (
    0 => '/PREVIEW',
    1 => '#^/PREVIEW$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'template',
      'action' => 'preview',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'article_shortcut' => 
  array (
    0 => '/articulo/:year/:month/:day/:name',
    1 => '#^/articulo(?:\\/([^\\/]+))?(?:\\/([^\\/]+))?(?:\\/([^\\/]+))?(?:\\/([^\\/]+))?$#',
    2 => 
    array (
      0 => 'year',
      1 => 'month',
      2 => 'day',
      3 => 'name',
    ),
    3 => 
    array (
      'year' => 1,
      'month' => 1,
      'day' => 1,
      'name' => 1,
    ),
    4 => 
    array (
      'module' => 'article',
      'action' => 'getArticleByName',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'article_by_id' => 
  array (
    0 => '/articulo/:id',
    1 => '#^/articulo(?:\\/([^\\/]+))?$#',
    2 => 
    array (
      0 => 'id',
    ),
    3 => 
    array (
      'id' => 1,
    ),
    4 => 
    array (
      'module' => 'article',
      'action' => 'getArticleById',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'article_popup' => 
  array (
    0 => '/articulo/popup/:id',
    1 => '#^/articulo/popup(?:\\/([^\\/]+))?$#',
    2 => 
    array (
      0 => 'id',
    ),
    3 => 
    array (
      'id' => 1,
    ),
    4 => 
    array (
      'module' => 'article',
      'action' => 'getArticleForPop',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'contact' => 
  array (
    0 => '/Contacto',
    1 => '#^/Contacto$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'contact',
      'action' => 'contactForm',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'show_all' => 
  array (
    0 => '/TodasLasNoticias/:page/*',
    1 => '#^/TodasLasNoticias(?:\\/([^\\/]+))?(?:\\/(.*))?$#',
    2 => 
    array (
      0 => 'page',
    ),
    3 => 
    array (
      'page' => 1,
    ),
    4 => 
    array (
      'module' => 'article',
      'action' => 'showAll',
      'page' => 1,
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'show_gallery' => 
  array (
    0 => '/Galeria/:gallery_id/:article_id',
    1 => '#^/Galeria(?:\\/([^\\/]+))?(?:\\/([^\\/]+))?$#',
    2 => 
    array (
      0 => 'gallery_id',
      1 => 'article_id',
    ),
    3 => 
    array (
      'gallery_id' => 1,
      'article_id' => 1,
    ),
    4 => 
    array (
      'module' => 'article',
      'action' => 'showGallery',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'search' => 
  array (
    0 => '/Buscar',
    1 => '#^/Buscar$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'sfLucene',
      'action' => 'search',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'search_xml' => 
  array (
    0 => '/search-xml',
    1 => '#^/search-xml$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'search',
      'action' => 'index',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'sitemap' => 
  array (
    0 => '/MapaDelSitio',
    1 => '#^/MapaDelSitio$#',
    2 => 
    array (
    ),
    3 => 
    array (
    ),
    4 => 
    array (
      'module' => 'sitemap',
      'action' => 'index',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'feed' => 
  array (
    0 => '/rss/:section',
    1 => '#^/rss(?:\\/([^\\/]+))?$#',
    2 => 
    array (
      0 => 'section',
    ),
    3 => 
    array (
      'section' => 1,
    ),
    4 => 
    array (
      'module' => 'feed',
      'action' => 'index',
      'section' => 'NONE',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'template_feed' => 
  array (
    0 => '/rss/list/:template',
    1 => '#^/rss/list(?:\\/([^\\/]+))?$#',
    2 => 
    array (
      0 => 'template',
    ),
    3 => 
    array (
      'template' => 1,
    ),
    4 => 
    array (
      'module' => 'feed',
      'action' => 'template',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'template_by_article' => 
  array (
    0 => '/article/:articleId',
    1 => '#^/article(?:\\/([^\\/]+))?$#',
    2 => 
    array (
      0 => 'articleId',
    ),
    3 => 
    array (
      'articleId' => 1,
    ),
    4 => 
    array (
      'module' => 'article',
      'action' => 'templateByArticle',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'template_by_name' => 
  array (
    0 => '/:name',
    1 => '#^(?:\\/([^\\/]+))?$#',
    2 => 
    array (
      0 => 'name',
    ),
    3 => 
    array (
      'name' => 1,
    ),
    4 => 
    array (
      'module' => 'section',
      'action' => 'templateByName',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'rss_view_more' => 
  array (
    0 => '/RssVerMas/:nombre/:id/:section',
    1 => '#^/RssVerMas(?:\\/([^\\/]+))?(?:\\/([^\\/]+))?(?:\\/([^\\/]+))?$#',
    2 => 
    array (
      0 => 'nombre',
      1 => 'id',
      2 => 'section',
    ),
    3 => 
    array (
      'nombre' => 1,
      'id' => 1,
      'section' => 1,
    ),
    4 => 
    array (
      'module' => 'rsslist',
      'action' => 'showAll',
      'section' => 'NONE',
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
  'default' => 
  array (
    0 => '/:module/:action/*',
    1 => '#^(?:\\/([^\\/]+))?(?:\\/([^\\/]+))?(?:\\/(.*))?$#',
    2 => 
    array (
      0 => 'module',
      1 => 'action',
    ),
    3 => 
    array (
      'module' => 1,
      'action' => 1,
    ),
    4 => 
    array (
    ),
    5 => 
    array (
    ),
    6 => '',
  ),
)
);
