<?php
// auto-generated by sfAdvancedAdmin
// date: 2015/10/30 10:56:51
?>
<ul class="sf_admin_actions">
    <li><?php echo button_to(__('list'), 'article/list?id='.$article->getId(), array (
  'class' => 'sf_admin_action_list',
)) ?></li>
    <li><?php echo submit_tag(__('Guardar y seguir editando'), array (
  'name' => 'save',
  'class' => 'sf_admin_action_save',
)) ?></li>
    <li><?php echo submit_tag(__('save and list'), array (
  'name' => 'save_and_list',
  'class' => 'sf_admin_action_save_and_list',
)) ?></li>
</ul>
