<?php
// auto-generated by sfAdvancedAdmin
// date: 2015/10/30 10:56:51
?>
<?php echo form_tag('article/edit', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
  'onsubmit'  => 'double_list_submit(); return true;'
)) ?>

<?php echo object_input_hidden_tag($article, 'getId') ?>

<fieldset id="sf_fieldset_informaci__n_y_estado" class="">
<h2><?php echo __('Información y estado') ?></h2>


<div class="form-row">
  <?php echo label_for('article[name]', __($labels['article{name}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('article{name}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('article{name}')): ?>
    <?php echo form_error('article{name}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($article, 'getName', array (
  'size' => 80,
  'control_name' => 'article[name]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
  <div style="clear:both; height: 1px; font-size: 1px;">&nbsp;</div>
</div>

<div class="form-row">
  <?php echo label_for('article[source_id]', __($labels['article{source_id}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('article{source_id}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('article{source_id}')): ?>
    <?php echo form_error('article{source_id}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_select_tag($article, 'getSourceId', array (
  'related_class' => 'Source',
  'control_name' => 'article[source_id]',
  'include_blank' => true,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
  <div style="clear:both; height: 1px; font-size: 1px;">&nbsp;</div>
</div>

<div class="form-row">
  <?php echo label_for('article[type_field]', __($labels['article{type_field}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('article{type_field}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('article{type_field}')): ?>
    <?php echo form_error('article{type_field}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = get_partial('type_field', array('type' => 'edit', 'article' => $article)); echo $value ? $value : '&nbsp;' ?>
    </div>
  <div style="clear:both; height: 1px; font-size: 1px;">&nbsp;</div>
</div>

<div class="form-row">
  <?php echo label_for('article[comment]', __($labels['article{comment}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('article{comment}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('article{comment}')): ?>
    <?php echo form_error('article{comment}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($article, 'getComment', array (
  'size' => '30x3',
  'control_name' => 'article[comment]',
)); echo $value ? $value : '&nbsp;' ?>
  <div class="sf_admin_edit_help"><?php echo __('Para uso interno') ?></div>  </div>
  <div style="clear:both; height: 1px; font-size: 1px;">&nbsp;</div>
</div>

</fieldset>
<fieldset id="sf_fieldset_categor__as" class="">
<h2><?php echo __('Categorías') ?></h2>


<div class="form-row">
  <?php echo label_for('article[article_tag]', __($labels['article{article_tag}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('article{article_tag}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('article{article_tag}')): ?>
    <?php echo form_error('article{article_tag}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_admin_double_list($article, 'getArticleTag', array (
  'control_name' => 'article[article_tag]',
  'through_class' => 'ArticleTag',
  'style' => 'width:350px;',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
  <div style="clear:both; height: 1px; font-size: 1px;">&nbsp;</div>
</div>

</fieldset>
<fieldset id="sf_fieldset_secciones_relacionadas" class="">
<h2><?php echo __('Secciones relacionadas') ?></h2>


<div class="form-row">
  <?php echo label_for('article[section_id]', __($labels['article{section_id}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('article{section_id}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('article{section_id}')): ?>
    <?php echo form_error('article{section_id}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = get_partial('section_id', array('type' => 'edit', 'article' => $article)); echo $value ? $value : '&nbsp;' ?>
    </div>
  <div style="clear:both; height: 1px; font-size: 1px;">&nbsp;</div>
</div>

<div class="form-row">
  <?php echo label_for('article[article_section]', __($labels['article{article_section}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('article{article_section}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('article{article_section}')): ?>
    <?php echo form_error('article{article_section}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = get_partial('article_section', array('type' => 'edit', 'article' => $article)); echo $value ? $value : '&nbsp;' ?>
    </div>
  <div style="clear:both; height: 1px; font-size: 1px;">&nbsp;</div>
</div>

</fieldset>
<fieldset id="sf_fieldset_contenido" class="">
<h2><?php echo __('Contenido') ?></h2>


<div class="form-row">
  <?php echo label_for('article[upper_description]', __($labels['article{upper_description}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('article{upper_description}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('article{upper_description}')): ?>
    <?php echo form_error('article{upper_description}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($article, 'getUpperDescription', array (
  'size' => 80,
  'control_name' => 'article[upper_description]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
  <div style="clear:both; height: 1px; font-size: 1px;">&nbsp;</div>
</div>

<div class="form-row">
  <?php echo label_for('article[title]', __($labels['article{title}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('article{title}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('article{title}')): ?>
    <?php echo form_error('article{title}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($article, 'getTitle', array (
  'size' => 80,
  'control_name' => 'article[title]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
  <div style="clear:both; height: 1px; font-size: 1px;">&nbsp;</div>
</div>

<div class="form-row">
  <?php echo label_for('article[heading]', __($labels['article{heading}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('article{heading}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('article{heading}')): ?>
    <?php echo form_error('article{heading}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($article, 'getHeading', array (
  'control_name' => 'article[heading]',
  'size' => '77x10',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
  <div style="clear:both; height: 1px; font-size: 1px;">&nbsp;</div>
</div>

<div class="form-row">
  <?php echo label_for('article[editor]', __($labels['article{editor}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('article{editor}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('article{editor}')): ?>
    <?php echo form_error('article{editor}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = get_partial('editor', array('type' => 'edit', 'article' => $article)); echo $value ? $value : '&nbsp;' ?>
    </div>
  <div style="clear:both; height: 1px; font-size: 1px;">&nbsp;</div>
</div>

<div class="form-row">
  <?php echo label_for('article[contact]', __($labels['article{contact}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('article{contact}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('article{contact}')): ?>
    <?php echo form_error('article{contact}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($article, 'getContact', array (
  'size' => 80,
  'control_name' => 'article[contact]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
  <div style="clear:both; height: 1px; font-size: 1px;">&nbsp;</div>
</div>

<div class="form-row">
  <?php echo label_for('article[multimedia_id]', __($labels['article{multimedia_id}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('article{multimedia_id}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('article{multimedia_id}')): ?>
    <?php echo form_error('article{multimedia_id}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = get_partial('multimedia_id', array('type' => 'edit', 'article' => $article)); echo $value ? $value : '&nbsp;' ?>
    </div>
  <div style="clear:both; height: 1px; font-size: 1px;">&nbsp;</div>
</div>

<div class="form-row">
  <?php echo label_for('article[zoomable_multimedia]', __($labels['article{zoomable_multimedia}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('article{zoomable_multimedia}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('article{zoomable_multimedia}')): ?>
    <?php echo form_error('article{zoomable_multimedia}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($article, 'getZoomableMultimedia', array (
  'size' => 7,
  'control_name' => 'article[zoomable_multimedia]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
  <div style="clear:both; height: 1px; font-size: 1px;">&nbsp;</div>
</div>

<div class="form-row">
  <?php echo label_for('article[main_gallery_id]', __($labels['article{main_gallery_id}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('article{main_gallery_id}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('article{main_gallery_id}')): ?>
    <?php echo form_error('article{main_gallery_id}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_select_tag($article, 'getMainGalleryId', array (
  'related_class' => 'Gallery',
  'control_name' => 'article[main_gallery_id]',
  'peer_method' => 'retrievePublished',
  'include_blank' => true,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
  <div style="clear:both; height: 1px; font-size: 1px;">&nbsp;</div>
</div>

<div class="form-row">
  <?php echo label_for('article[reference_type]', __($labels['article{reference_type}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('article{reference_type}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('article{reference_type}')): ?>
    <?php echo form_error('article{reference_type}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = get_partial('reference_type', array('type' => 'edit', 'article' => $article)); echo $value ? $value : '&nbsp;' ?>
    </div>
  <div style="clear:both; height: 1px; font-size: 1px;">&nbsp;</div>
</div>

<div class="form-row">
  <?php echo label_for('article[reference]', __($labels['article{reference}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('article{reference}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('article{reference}')): ?>
    <?php echo form_error('article{reference}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = get_partial('reference', array('type' => 'edit', 'article' => $article)); echo $value ? $value : '&nbsp;' ?>
  <div class="sf_admin_edit_help"><?php echo __('Reemplazará el vínculo al artículo en cada referencia al mismo') ?></div>  </div>
  <div style="clear:both; height: 1px; font-size: 1px;">&nbsp;</div>
</div>

<div class="form-row">
  <?php echo label_for('article[open_reference_new_window]', __($labels['article{open_reference_new_window}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('article{open_reference_new_window}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('article{open_reference_new_window}')): ?>
    <?php echo form_error('article{open_reference_new_window}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($article, 'getOpenReferenceNewWindow', array (
  'size' => 7,
  'control_name' => 'article[open_reference_new_window]',
)); echo $value ? $value : '&nbsp;' ?>
  <div class="sf_admin_edit_help"><?php echo __('Utilice está opción si desea que los enlaces al articulo se abran en nuevas ventanas') ?></div>  </div>
  <div style="clear:both; height: 1px; font-size: 1px;">&nbsp;</div>
</div>

</fieldset>
<fieldset id="sf_fieldset_tareas_autom__ticas" class="">
<h2><?php echo __('Tareas Automáticas') ?></h2>


<div class="form-row">
  <?php echo label_for('article[auto_publish_at]', __($labels['article{auto_publish_at}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('article{auto_publish_at}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('article{auto_publish_at}')): ?>
    <?php echo form_error('article{auto_publish_at}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_date_tag($article, 'getAutoPublishAt', array (
  'rich' => true,
  'withtime' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'article[auto_publish_at]',
  'date_format' => 'dd/MM/yyyy H:mm',
)); echo $value ? $value : '&nbsp;' ?>
  <div class="sf_admin_edit_help"><?php echo __('Si desea que el articulo se publique automáticamente seleccione la fecha y la hora') ?></div>  </div>
  <div style="clear:both; height: 1px; font-size: 1px;">&nbsp;</div>
</div>

<div class="form-row">
  <?php echo label_for('article[auto_unpublish_at]', __($labels['article{auto_unpublish_at}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('article{auto_unpublish_at}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('article{auto_unpublish_at}')): ?>
    <?php echo form_error('article{auto_unpublish_at}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_date_tag($article, 'getAutoUnpublishAt', array (
  'rich' => true,
  'withtime' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'article[auto_unpublish_at]',
  'date_format' => 'dd/MM/yyyy H:mm',
)); echo $value ? $value : '&nbsp;' ?>
  <div class="sf_admin_edit_help"><?php echo __('Si desea que el articulo se despublique automáticamente seleccione la fecha y la hora') ?></div>  </div>
  <div style="clear:both; height: 1px; font-size: 1px;">&nbsp;</div>
</div>

</fieldset>

<?php include_partial('edit_actions', array('article' => $article)) ?>

</form>

<ul class="sf_admin_actions">
  </ul>
