<?php
// auto-generated by sfAdvancedAdmin
// date: 2015/11/10 10:39:01
?>
<?php use_helper('Object', 'Javascript') ?>

<?php echo javascript_tag(sprintf("function toggle_filters() { $('filters_hidden_area').toggleClassName('hidden'); var src = ($('filters_hidden_area').hasClassName('hidden') ? '%s' : '%s'); $('sf_admin_filters_arrow').src = src; }", image_path('backend/bullet_arrow_down.png'), image_path('backend/bullet_arrow_up.png'))) ?>

<div class="sf_admin_filters">
<?php echo form_tag('article/list', array('method' => 'get')) ?>

  <fieldset>
    <h2><?php echo link_to_function(image_tag('backend/bullet_arrow_down.png', array('alt' => '', 'id' => 'sf_admin_filters_arrow')) . __('filters'), "toggle_filters();") ?></h2>

    <div id="filters_hidden_area" class="hidden">

    <div class="form-row">
    <label for="title"><?php echo __('Título:') ?></label>
    <div class="content">
    <?php echo input_tag('filters[title]', isset($filters['title']) ? $filters['title'] : null, array (
  'size' => 15,
)) ?>
    <div class="sf_admin_edit_help"><?php echo __('Utilice * como wildcard') ?></div>    </div>
    <div style="clear: both; height: 1px; font-size: 1px;">&nbsp;</div>
    </div>

        <div class="form-row">
    <label for="name"><?php echo __('Nombre:') ?></label>
    <div class="content">
    <?php echo input_tag('filters[name]', isset($filters['name']) ? $filters['name'] : null, array (
  'size' => 15,
)) ?>
    <div class="sf_admin_edit_help"><?php echo __('Utilice * como wildcard') ?></div>    </div>
    <div style="clear: both; height: 1px; font-size: 1px;">&nbsp;</div>
    </div>

        <div class="form-row">
    <label for="type"><?php echo __('Tipo:') ?></label>
    <div class="content">
    <?php echo get_partial('type', array('type' => 'filter', 'filters' => $filters)) ?>
        </div>
    <div style="clear: both; height: 1px; font-size: 1px;">&nbsp;</div>
    </div>

        <div class="form-row">
    <label for="is_published"><?php echo __('Publicado:') ?></label>
    <div class="content">
    <?php echo input_tag('filters[is_published]', isset($filters['is_published']) ? $filters['is_published'] : null, array (
  'size' => 7,
)) ?>
        </div>
    <div style="clear: both; height: 1px; font-size: 1px;">&nbsp;</div>
    </div>

        <div class="form-row">
    <label for="is_deleted"><?php echo __('Borrado:') ?></label>
    <div class="content">
    <?php echo input_tag('filters[is_deleted]', isset($filters['is_deleted']) ? $filters['is_deleted'] : null, array (
  'disabled' => true,
)) ?>
        </div>
    <div style="clear: both; height: 1px; font-size: 1px;">&nbsp;</div>
    </div>

        <div class="form-row">
    <label for="is_archived"><?php echo __('Archivado:') ?></label>
    <div class="content">
    <?php echo input_tag('filters[is_archived]', isset($filters['is_archived']) ? $filters['is_archived'] : null, array (
  'size' => 7,
)) ?>
        </div>
    <div style="clear: both; height: 1px; font-size: 1px;">&nbsp;</div>
    </div>

        <div class="form-row">
    <label for="section_id"><?php echo __('Sección:') ?></label>
    <div class="content">
    <?php echo get_partial('section_id', array('type' => 'filter', 'filters' => $filters)) ?>
        </div>
    <div style="clear: both; height: 1px; font-size: 1px;">&nbsp;</div>
    </div>

        <div class="form-row">
    <label for="created_by"><?php echo __('Autor:') ?></label>
    <div class="content">
    <?php echo object_select_tag(isset($filters['created_by']) ? $filters['created_by'] : null, null, array (
  'include_blank' => true,
  'related_class' => 'sfGuardUser',
  'text_method' => '__toString',
  'control_name' => 'filters[created_by]',
)) ?>
        </div>
    <div style="clear: both; height: 1px; font-size: 1px;">&nbsp;</div>
    </div>

        <div class="form-row">
    <label for="updated_at"><?php echo __('Última actualización:') ?></label>
    <div class="content">
    <?php echo input_date_range_tag('filters[updated_at]', isset($filters['updated_at']) ? $filters['updated_at'] : null, array (
  'rich' => true,
  'withtime' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'date_format' => 'dd/MM/yyyy H:mm',
)) ?>
        </div>
    <div style="clear: both; height: 1px; font-size: 1px;">&nbsp;</div>
    </div>

    
    </div>
  </fieldset>

  <ul class="sf_admin_actions">
    <li><?php echo button_to(__('reset'), 'article/list?filter=filter', 'class=sf_admin_action_reset_filter') ?></li>
    <li><?php echo submit_tag(__('filter'), 'name=filter class=sf_admin_action_filter') ?></li>
  </ul>

</form>
</div>
