<?php
// auto-generated by sfAdvancedAdmin
// date: 2015/11/10 10:39:01
?>
<ul class="sf_admin_actions">
      <li><?php echo button_to(__('create'), 'article/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
  </ul>
