<?php
// auto-generated by sfAdvancedAdmin
// date: 2015/10/30 10:56:51
?>
<ul class="sf_admin_actions">
      <li><?php echo button_to(__('create'), 'article/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
  </ul>
