<?php
// auto-generated by sfAdvancedAdmin
// date: 2015/11/10 10:39:01
?>
<?php $sort_array = $sf_user->getAttributeHolder()->getAll('sf_admin/article/sort'); ?>
  <th id="sf_admin_list_th_name">
    <?php if (isset($sort_array['name'])) : ?>
      <?php $order = ($sort_array['name']); ?>
      <?php echo link_to(__('Nombre'), 'article/list?sort=name&type='.($order == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo $order ?>)
    <?php else: ?>
      <?php echo link_to('Nombre', 'article/list?sort=name&type=asc') ?>
    <?php endif; ?>
      </th>
  <th id="sf_admin_list_th_title">
    <?php if (isset($sort_array['title'])) : ?>
      <?php $order = ($sort_array['title']); ?>
      <?php echo link_to(__('Título'), 'article/list?sort=title&type='.($order == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo $order ?>)
    <?php else: ?>
      <?php echo link_to('Título', 'article/list?sort=title&type=asc') ?>
    <?php endif; ?>
      </th>
  <th id="sf_admin_list_th_author">
    <?php if (isset($sort_array['author'])) : ?>
      <?php $order = ($sort_array['author']); ?>
      <?php echo link_to(__('Autor'), 'article/list?sort=author&type='.($order == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo $order ?>)
    <?php else: ?>
      <?php echo link_to('Autor', 'article/list?sort=author&type=asc') ?>
    <?php endif; ?>
      </th>
  <th id="sf_admin_list_th_type_text">
    <?php if (isset($sort_array['type_text'])) : ?>
      <?php $order = ($sort_array['type_text']); ?>
      <?php echo link_to(__('Tipo'), 'article/list?sort=type_text&type='.($order == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo $order ?>)
    <?php else: ?>
      <?php echo link_to('Tipo', 'article/list?sort=type_text&type=asc') ?>
    <?php endif; ?>
      </th>
  <th id="sf_admin_list_th_section">
    <?php echo __('Sección') ?>
      </th>
  <th id="sf_admin_list_th_multimedia">
    <?php echo __('Imagen destacada') ?>
      </th>
  <th id="sf_admin_list_th_current_status">
    <?php echo __('Estado') ?>
      </th>
  <th id="sf_admin_list_th_updated_at">
    <?php if (isset($sort_array['updated_at'])) : ?>
      <?php $order = ($sort_array['updated_at']); ?>
      <?php echo link_to(__('Última actualización'), 'article/list?sort=updated_at&type='.($order == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo $order ?>)
    <?php else: ?>
      <?php echo link_to('Última actualización', 'article/list?sort=updated_at&type=asc') ?>
    <?php endif; ?>
      </th>
  <th id="sf_admin_list_th_created_at">
    <?php if (isset($sort_array['created_at'])) : ?>
      <?php $order = ($sort_array['created_at']); ?>
      <?php echo link_to(__('Fecha de creación'), 'article/list?sort=created_at&type='.($order == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo $order ?>)
    <?php else: ?>
      <?php echo link_to('Fecha de creación', 'article/list?sort=created_at&type=asc') ?>
    <?php endif; ?>
      </th>
