<?php
// auto-generated by sfAdvancedAdmin
// date: 2015/08/19 15:56:59
?>
<td>
<ul class="sf_admin_td_actions">
  <li><?php echo link_to(image_tag('/sf/sf_admin/images/filter.png', array('alt' => __('show'), 'title' => __('show'))), 'article/show?id='.$article->getId()) ?></li>
  <?php if ($article->canEdit()): ?>
  <li><?php echo link_to(image_tag('/sf/sf_admin/images/edit_icon.png', array('alt' => __('edit'), 'title' => __('edit'))), 'article/edit?id='.$article->getId()) ?></li>
  <?php endif ?>
  <?php if ($article->canUnpublish()): ?>
  <?php if ($sf_user->hasCredential(array (   0 =>    array (     0 => 'reporter_admin',     1 => 'designer_admin',   ), ))): ?>
<li><?php echo link_to(image_tag('/sf/sf_admin/images/default_icon.png', array('alt' => __('Despublicar'), 'title' => __('Despublicar'))), 'article/unpublish?id='.$article->getId()) ?></li>

<?php endif; ?>  <?php endif ?>
  <?php if ($article->canPublish()): ?>
  <?php if ($sf_user->hasCredential(array (   0 =>    array (     0 => 'reporter_admin',     1 => 'designer_admin',   ), ))): ?>
<li><?php echo link_to(image_tag('backend/publish_icon.png', array('alt' => __('Publicar'), 'title' => __('Publicar'))), 'article/publish?id='.$article->getId()) ?></li>

<?php endif; ?>  <?php endif ?>
  <?php if ($article->canArchive()): ?>
  <?php if ($sf_user->hasCredential(array (   0 =>    array (     0 => 'reporter_admin',     1 => 'designer_admin',   ), ))): ?>
<li><?php echo link_to(image_tag('backend/archive_icon.png', array('alt' => __('Archivar'), 'title' => __('Archivar'))), 'article/archive?id='.$article->getId()) ?></li>

<?php endif; ?>  <?php endif ?>
  <li><?php echo link_to(image_tag('backend/magnifier.png', array('alt' => __('Previsualizar articulo'), 'title' => __('Previsualizar articulo'))), 'article/preview?id='.$article->getId(), array (
  'popup' => true,
)) ?></li>
  <?php if ($article->canDelete()): ?>
  <li><?php echo link_to(image_tag('/sf/sf_admin/images/delete_icon.png', array('alt' => __('delete'), 'title' => __('delete'))), 'article/delete?id='.$article->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
)) ?></li>
  <?php endif ?>
  <li><?php echo link_to(image_tag('backend/copy.png', array('alt' => __('Copia un articulo'), 'title' => __('Copia un articulo'))), 'article/copy?id='.$article->getId()) ?></li>
</ul>
</td>
