<?php
// auto-generated by sfAdvancedAdmin
// date: 2015/08/19 15:56:59
?>
<fieldset id="sf_fieldset_informaci__n_y_estado" class="">
<h2><?php echo __('Información y estado') ?></h2>


<div class="form-row">
  <?php echo label_for('article[source]', __($labels['article{source}']), 'class="required" ') ?>
  <div class="content">
  <?php $value = (null !== ($val = $article->getSource()) && isset($maps["source"][$val])?$maps["source"][$val]:$val); echo $value ? $value : '&nbsp;' ?>
    </div>
  <div style="clear:both; height: 1px; font-size: 1px;">&nbsp;</div>
</div>

<div class="form-row">
  <?php echo label_for('article[type_text]', __($labels['article{type_text}']), 'class="required" ') ?>
  <div class="content">
  <?php $value = (null !== ($val = $article->getTypeText()) && isset($maps["type_text"][$val])?$maps["type_text"][$val]:$val); echo $value ? $value : '&nbsp;' ?>
    </div>
  <div style="clear:both; height: 1px; font-size: 1px;">&nbsp;</div>
</div>

<div class="form-row">
  <?php echo label_for('article[comment]', __($labels['article{comment}']), 'class="required" ') ?>
  <div class="content">
  <?php $value = (null !== ($val = $article->getComment()) && isset($maps["comment"][$val])?$maps["comment"][$val]:$val); echo $value ? $value : '&nbsp;' ?>
    </div>
  <div style="clear:both; height: 1px; font-size: 1px;">&nbsp;</div>
</div>

<div class="form-row">
  <?php echo label_for('article[current_status]', __($labels['article{current_status}']), 'class="required" ') ?>
  <div class="content">
  <?php $value = (null !== ($val = $article->getCurrentStatus()) && isset($maps["current_status"][$val])?$maps["current_status"][$val]:$val); echo $value ? $value : '&nbsp;' ?>
    </div>
  <div style="clear:both; height: 1px; font-size: 1px;">&nbsp;</div>
</div>

<div class="form-row">
  <?php echo label_for('article[section]', __($labels['article{section}']), 'class="required" ') ?>
  <div class="content">
  <?php $value = (null !== ($val = $article->getSection()) && isset($maps["section"][$val])?$maps["section"][$val]:$val); echo $value ? $value : '&nbsp;' ?>
    </div>
  <div style="clear:both; height: 1px; font-size: 1px;">&nbsp;</div>
</div>

<div class="form-row">
  <?php echo label_for('article[references]', __($labels['article{references}']), 'class="required" ') ?>
  <div class="content">
  <?php $value = get_partial('references', array('type' => 'list', 'article' => $article)); echo $value ? $value : '&nbsp;' ?>
    </div>
  <div style="clear:both; height: 1px; font-size: 1px;">&nbsp;</div>
</div>

<div class="form-row">
  <?php echo label_for('article[open_as_popup]', __($labels['article{open_as_popup}']), 'class="required" ') ?>
  <div class="content">
  <?php $value = (null !== ($val = $article->getOpenAsPopup() ? image_tag(sfConfig::get('sf_admin_web_dir').'/images/tick.png') : '&nbsp;') && isset($maps["open_as_popup"][$val])?$maps["open_as_popup"][$val]:$val); echo $value ? $value : '&nbsp;' ?>
  <div class="sf_admin_edit_help"><?php echo __('Utilice está opción para hacer que el Articulo se abra en una nueva ventana al entrar al HOME') ?></div>  </div>
  <div style="clear:both; height: 1px; font-size: 1px;">&nbsp;</div>
</div>

</fieldset>
<fieldset id="sf_fieldset_informaci__n_de_auditoria" class="">
<h2><?php echo __('Información de Auditoria') ?></h2>


<div class="form-row">
  <?php echo label_for('article[author]', __($labels['article{author}']), 'class="required" ') ?>
  <div class="content">
  <?php $value = (null !== ($val = $article->getAuthor()) && isset($maps["author"][$val])?$maps["author"][$val]:$val); echo $value ? $value : '&nbsp;' ?>
    </div>
  <div style="clear:both; height: 1px; font-size: 1px;">&nbsp;</div>
</div>

<div class="form-row">
  <?php echo label_for('article[created_at]', __($labels['article{created_at}']), 'class="required" ') ?>
  <div class="content">
  <?php $value = (null !== ($val = ($article->getCreatedAt() !== null && $article->getCreatedAt() !== '') ? format_date($article->getCreatedAt(), "dd/MM/yyyy H:mm") : '') && isset($maps["created_at"][$val])?$maps["created_at"][$val]:$val); echo $value ? $value : '&nbsp;' ?>
    </div>
  <div style="clear:both; height: 1px; font-size: 1px;">&nbsp;</div>
</div>

<div class="form-row">
  <?php echo label_for('article[author_updated]', __($labels['article{author_updated}']), 'class="required" ') ?>
  <div class="content">
  <?php $value = (null !== ($val = $article->getAuthorUpdated()) && isset($maps["author_updated"][$val])?$maps["author_updated"][$val]:$val); echo $value ? $value : '&nbsp;' ?>
    </div>
  <div style="clear:both; height: 1px; font-size: 1px;">&nbsp;</div>
</div>

<div class="form-row">
  <?php echo label_for('article[updated_at]', __($labels['article{updated_at}']), 'class="required" ') ?>
  <div class="content">
  <?php $value = (null !== ($val = ($article->getUpdatedAt() !== null && $article->getUpdatedAt() !== '') ? format_date($article->getUpdatedAt(), "dd/MM/yyyy H:mm") : '') && isset($maps["updated_at"][$val])?$maps["updated_at"][$val]:$val); echo $value ? $value : '&nbsp;' ?>
    </div>
  <div style="clear:both; height: 1px; font-size: 1px;">&nbsp;</div>
</div>

</fieldset>
<fieldset id="sf_fieldset_contenido" class="">
<h2><?php echo __('Contenido') ?></h2>


<div class="form-row">
  <?php echo label_for('article[full_html_representation]', __($labels['article{full_html_representation}']), 'class="required" ') ?>
  <div class="content">
  <?php $value = (null !== ($val = $article->getFullHTMLRepresentation()) && isset($maps["full_html_representation"][$val])?$maps["full_html_representation"][$val]:$val); echo $value ? $value : '&nbsp;' ?>
    </div>
  <div style="clear:both; height: 1px; font-size: 1px;">&nbsp;</div>
</div>

</fieldset>
<fieldset id="sf_fieldset_tareas_autom__ticas" class="">
<h2><?php echo __('Tareas Automáticas') ?></h2>


<div class="form-row">
  <?php echo label_for('article[auto_publish_at]', __($labels['article{auto_publish_at}']), 'class="required" ') ?>
  <div class="content">
  <?php $value = (null !== ($val = ($article->getAutoPublishAt() !== null && $article->getAutoPublishAt() !== '') ? format_date($article->getAutoPublishAt(), "dd/MM/yyyy H:mm") : '') && isset($maps["auto_publish_at"][$val])?$maps["auto_publish_at"][$val]:$val); echo $value ? $value : '&nbsp;' ?>
  <div class="sf_admin_edit_help"><?php echo __('Si desea que el articulo se publique automáticamente seleccione la fecha y la hora') ?></div>  </div>
  <div style="clear:both; height: 1px; font-size: 1px;">&nbsp;</div>
</div>

<div class="form-row">
  <?php echo label_for('article[auto_unpublish_at]', __($labels['article{auto_unpublish_at}']), 'class="required" ') ?>
  <div class="content">
  <?php $value = (null !== ($val = ($article->getAutoUnpublishAt() !== null && $article->getAutoUnpublishAt() !== '') ? format_date($article->getAutoUnpublishAt(), "dd/MM/yyyy H:mm") : '') && isset($maps["auto_unpublish_at"][$val])?$maps["auto_unpublish_at"][$val]:$val); echo $value ? $value : '&nbsp;' ?>
  <div class="sf_admin_edit_help"><?php echo __('Si desea que el articulo se despublique automáticamente seleccione la fecha y la hora') ?></div>  </div>
  <div style="clear:both; height: 1px; font-size: 1px;">&nbsp;</div>
</div>

</fieldset>

<?php include_partial('show_actions', array('article' => $article)) ?>
