<?php
// auto-generated by sfAdvancedAdmin
// date: 2015/11/10 10:39:01
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date', 'AdvancedAdmin') ?>

<?php use_stylesheet('backend/admin_theme_black') ?>

<div id="sf_admin_container">

<h1><?php echo __('Crear un nuevo artículo', 
array()) ?></h1>

<div id="sf_admin_header">
<?php include_partial('article/create_header', array('article' => $article)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('article/create_messages', array('article' => $article, 'labels' => $labels)) ?>
<?php include_partial('article/create_form', array('article' => $article, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('article/create_footer', array('article' => $article)) ?>
</div>

</div>
