<?php
// auto-generated by sfAdvancedAdmin
// date: 2015/10/30 10:56:51
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date', 'AdvancedAdmin') ?>

<?php use_stylesheet('backend/admin_theme_black') ?>

<div id="sf_admin_container">

<h1><?php echo __('Editar artículo "%%name%%"', 
array('%%name%%' => (null !== ($val = $article->getName()) && isset($maps["name"][$val])?$maps["name"][$val]:$val))) ?></h1>

<div id="sf_admin_header">
<?php include_partial('article/edit_header', array('article' => $article)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('article/edit_messages', array('article' => $article, 'labels' => $labels)) ?>
<?php include_partial('article/edit_form', array('article' => $article, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('article/edit_footer', array('article' => $article)) ?>
</div>

</div>
