<?php
// auto-generated by sfAdvancedAdmin
// date: 2015/10/30 10:56:51
?>
<?php use_helper('I18N', 'Date') ?>

<?php use_stylesheet('backend/admin_theme_black') ?>

<div id="sf_admin_container">

<h1><?php echo __('Listado de artículos', 
array()) ?></h1>

<div id="sf_admin_header">
<?php include_partial('article/list_header', array('pager' => $pager)) ?>
<?php include_partial('article/list_messages', array('pager' => $pager)) ?>
</div>

<div id="sf_admin_bar">
<?php include_partial('filters', array('filters' => $filters)) ?>
</div>

<div id="sf_admin_content">
<?php if (!$pager->getNbResults()): ?>
<?php echo __('no result') ?>
<?php else: ?>
<?php include_partial('article/list', array('pager' => $pager, 'maps' => $maps)) ?>
<?php endif; ?>
<?php include_partial('list_batch_actions') ?>
<?php include_partial('list_actions') ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('article/list_footer', array('pager' => $pager)) ?>
</div>

</div>
