<?php
// auto-generated by sfAdvancedAdmin
// date: 2015/11/10 10:39:01
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('backend/admin_theme_black') ?>

<div id="sf_admin_container">

<h1><?php echo __('Detalle del artículo "%%name%%"', 
array('%%name%%' => (null !== ($val = $article->getName()) && isset($maps["name"][$val])?$maps["name"][$val]:$val))) ?></h1>

<div id="sf_admin_header">
<?php include_partial('article/show_header', array('article' => $article)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('article/show', array('article' => $article, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('article/show_footer', array('article' => $article)) ?>
</div>

</div>
